name: CodeClub Deloyment

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: https://www.codeclub.top
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setting SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Scan public keys
        run: ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: ${{ vars.HUGO_VERSION }}
          extended: true
      - name: Build
        run: hugo --gc --minify -b https://${{ secrets.HOSTNAME }}
      - name: Install Rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Deploy
        run: rsync -avz --delete public/ ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/var/www/html
